# Generated by Django 3.2.16 on 2022-10-16 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_moblie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='moblie',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
