# Generated by Django 3.2.16 on 2022-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20221101_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='assigned_staff_member',
            field=models.CharField(choices=[('Gareth', 'Gareth'), ('Emily', 'Emily'), ('Rodger', 'Rodger'), ('Greg', 'Greg'), ('Alan', 'Alan'), ('Stevephen', 'Stevephen'), ('Patrick', 'Patrick')], default='Greg', max_length=50),
        ),
    ]
