# Generated by Django 3.2.16 on 2022-10-16 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_moblie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='moblie',
            field=models.PositiveBigIntegerField(default=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
