# Generated by Django 3.2.16 on 2022-10-16 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_moblie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='moblie',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
