# Generated by Django 3.2.16 on 2022-10-16 14:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_moblie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='moblie',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
