# Generated by Django 3.2.16 on 2022-10-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='whom_with',
            new_name='assigned_staff_member',
        ),
    ]
