# Generated by Django 3.2.16 on 2022-10-24 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_whom_with_booking_assigned_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
